############################################################
## 13_00_prepare_biological_heatmap_inputs.R
## MASTER INPUT BUILDER for biological heatmaps
##
## PURPOSE
##   Build one publication-oriented annotation/analysis master table that
##   connects the CURRENT WGCNA + maSigPro analyses with the biological
##   annotation logic used in the former scripts 09A / 09B / 09C / 10.
##
## THIS SCRIPT DOES NOT DRAW THE FINAL HEATMAPS.
## It prepares the common inputs that will be consumed by:
##   13A_HSP_module_heatmaps.R
##   13B_TF_module_heatmaps.R
##   13C_Immune_defence_module_heatmaps.R
##   14_Functional_module_heatmaps.R
##
## CORE PRINCIPLE
##   Statistical recruitment and biological annotation are kept separate.
##   A module is first classified from its experimental effects
##   (Temperature / Treatment / Time / interactions). Biological labels
##   (HSP, TF, immunity, pathways) are then added at gene level.
##
## CURRENT EXPERIMENT
##   WGCNA: D2/P2 + D4/P3
##   maSigPro: D0/P1 + D2/P2 + D4/P3, with D0 Control shared as the
##             baseline of the Control and Treated trajectories.
# Repository configuration (portable; no HPC-specific paths)
if (!exists('CARROT_CONFIG_LOADED')) source('../../../config/config.R')


############################################################

##############################
## 0. USER SETTINGS
##############################
PROJECT_ROOT <- OUTPUT_ROOT
WGCNA_ROOT <- RNA_WGCNA_ROOT
MASIGPRO_ROOT <- MASIGPRO_ROOT

## Annotation resources. These are generated by scripts/annotation_builders/
## or supplied as external carrot annotation tables.
LEGACY_P1_ROOT <- ANNOTATION_BUILDER_OUTPUT
MAP_FILE <- GENE_ID_MAP_FILE
HSP_ANNOT_FILE <- HSP_ANNOT_FILE
FUNCTIONAL_INPUT_DIR <- FUNCTIONAL_INPUT_DIR

## Optional manual paths. Leave NA for automatic detection.
PRESTO_WGCNA <- NA_character_
ROBILA_WGCNA <- NA_character_
PRESTO_MASIG <- NA_character_
ROBILA_MASIG <- NA_character_
WGCNA_COMPARATIVE_RUN <- NA_character_
WGCNA_MASIGPRO_RUN <- NA_character_

FDR_CUTOFF <- 0.05
STRICT_MASIGPRO_ONLY <- TRUE
KME_HUB_CUTOFF <- 0.85
GS_PRIORITY_CUTOFF <- 0.30

## Output
MASTER_ROOT <- BIOLOGICAL_HEATMAP_ROOT
TIMESTAMP <- format(Sys.time(), "%Y%m%d_%H%M%S")
OUT_DIR <- file.path(MASTER_ROOT, paste0("Biological_Master_", TIMESTAMP))
DIR_TABLES <- file.path(OUT_DIR, "01_tables")
DIR_EXPR   <- file.path(OUT_DIR, "02_expression_matrices")
DIR_ANNOT  <- file.path(OUT_DIR, "03_annotation_sources")
DIR_QC     <- file.path(OUT_DIR, "04_QC")
for (d in c(MASTER_ROOT, OUT_DIR, DIR_TABLES, DIR_EXPR, DIR_ANNOT, DIR_QC)) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

options(stringsAsFactors = FALSE)

##############################
## 1. PACKAGES
##############################
required_pkgs <- c("dplyr", "tidyr", "tibble", "readr", "stringr", "purrr")
missing_pkgs <- required_pkgs[
  !vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_pkgs)) {
  stop("Missing packages: ", paste(missing_pkgs, collapse = ", "))
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(readr)
  library(stringr)
  library(purrr)
})

##############################
## 2. HELPERS
##############################
log_file <- file.path(OUT_DIR, "13_00_master_builder.log")
log_msg <- function(...) {
  txt <- paste0("[", format(Sys.time(), "%H:%M:%S"), "] ", paste0(..., collapse = ""))
  cat(txt, "\n")
  cat(txt, "\n", file = log_file, append = TRUE)
}

assert_file <- function(path, label = "file") {
  if (is.na(path) || !file.exists(path)) stop(label, " not found: ", path)
  invisible(path)
}

read_csv_flexible <- function(path) {
  assert_file(path, "Input file")
  x <- tryCatch(
    readr::read_csv(path, show_col_types = FALSE, progress = FALSE),
    error = function(e) NULL
  )
  if (is.null(x) || ncol(x) <= 1L) {
    x <- readr::read_delim(path, delim = ";", show_col_types = FALSE, progress = FALSE)
  }
  as.data.frame(x, stringsAsFactors = FALSE)
}

safe_read_csv <- function(path) {
  if (!file.exists(path)) return(data.frame())
  read_csv_flexible(path)
}

latest_matching_dir <- function(root, pattern, recursive = TRUE) {
  if (!dir.exists(root)) return(NA_character_)
  dd <- list.dirs(root, recursive = recursive, full.names = TRUE)
  hit <- dd[grepl(pattern, basename(dd))]
  if (!length(hit)) return(NA_character_)
  hit[order(file.info(hit)$mtime, decreasing = TRUE)][1]
}

latest_named_file <- function(roots, filename) {
  roots <- roots[dir.exists(roots)]
  if (!length(roots)) return(NA_character_)
  hits <- unlist(lapply(roots, function(root) {
    list.files(root, recursive = TRUE, full.names = TRUE, pattern = paste0("^", gsub("\\.", "\\\\.", filename), "$"))
  }), use.names = FALSE)
  hits <- hits[file.exists(hits)]
  if (!length(hits)) return(NA_character_)
  hits[order(file.info(hits)$mtime, decreasing = TRUE)][1]
}

find_masig_dir <- function(genotype) {
  exact <- file.path(MASIGPRO_ROOT, paste0(genotype, "_maSigPro"))
  if (dir.exists(exact)) return(exact)
  z <- latest_matching_dir(MASIGPRO_ROOT, paste0("^", genotype, "_maSigPro$"))
  if (!is.na(z)) return(z)
  latest_matching_dir(PROJECT_ROOT, paste0("^", genotype, "_maSigPro$"))
}

clean_gene <- function(x) trimws(as.character(x))

first_existing_col <- function(x, candidates) {
  z <- intersect(candidates, colnames(x))
  if (!length(z)) return(NA_character_)
  z[1]
}

collapse_unique <- function(x, sep = "; ") {
  x <- unique(trimws(as.character(x)))
  x <- x[!is.na(x) & nzchar(x)]
  if (!length(x)) return(NA_character_)
  paste(sort(x), collapse = sep)
}

normalise_temp_display <- function(x) {
  x <- as.character(x)
  dplyr::recode(x, "T0" = "NH", "T1" = "HS-7", "T2" = "HS-2", .default = x)
}
normalise_trt_display <- function(x) {
  x <- toupper(trimws(as.character(x)))
  dplyr::case_when(
    x %in% c("EAU", "WATER", "H2O", "CTRL", "CONTROL") ~ "Control",
    x %in% c("SDP", "TREATED") ~ "Treated",
    TRUE ~ stringr::str_to_title(tolower(x))
  )
}
normalise_time_display <- function(x) {
  x <- as.character(x)
  dplyr::recode(x, "P1" = "D0", "P2" = "D2", "P3" = "D4", .default = x)
}

##############################
## 3. LOCATE CURRENT ANALYSIS RUNS
##############################
if (is.na(PRESTO_WGCNA)) PRESTO_WGCNA <- latest_matching_dir(WGCNA_ROOT, "^WGCNA_PRESTO_P2P3_")
if (is.na(ROBILA_WGCNA)) ROBILA_WGCNA <- latest_matching_dir(WGCNA_ROOT, "^WGCNA_ROBILA_P2P3_")
if (is.na(PRESTO_MASIG)) PRESTO_MASIG <- find_masig_dir("PRESTO")
if (is.na(ROBILA_MASIG)) ROBILA_MASIG <- find_masig_dir("ROBILA")

if (is.na(WGCNA_COMPARATIVE_RUN)) {
  candidates <- list.dirs(WGCNA_ROOT, recursive = TRUE, full.names = TRUE)
  candidates <- candidates[grepl("^Integration_v2_", basename(candidates))]
  if (length(candidates)) {
    WGCNA_COMPARATIVE_RUN <- candidates[order(file.info(candidates)$mtime, decreasing = TRUE)][1]
  }
}

if (is.na(WGCNA_MASIGPRO_RUN)) {
  WGCNA_MASIGPRO_RUN <- latest_matching_dir(WGCNA_ROOT, "^WGCNA_maSigPro_Integration_")
}

for (x in c(PRESTO_WGCNA, ROBILA_WGCNA, PRESTO_MASIG, ROBILA_MASIG)) {
  if (is.na(x) || !dir.exists(x)) stop("Required current-analysis directory not found: ", x)
}

log_msg("PRESTO WGCNA: ", PRESTO_WGCNA)
log_msg("ROBILA WGCNA: ", ROBILA_WGCNA)
log_msg("PRESTO maSigPro: ", PRESTO_MASIG)
log_msg("ROBILA maSigPro: ", ROBILA_MASIG)
log_msg("WGCNA comparative: ", WGCNA_COMPARATIVE_RUN)
log_msg("WGCNA x maSigPro: ", WGCNA_MASIGPRO_RUN)

##############################
## 4. LOAD WGCNA GENE-LEVEL INFORMATION
##############################
load_wgcna_gene_info <- function(genotype, run_dir) {
  gene_mod <- read_csv_flexible(file.path(run_dir, "02_network", "Gene_to_Module.csv")) |>
    dplyr::mutate(
      Gene = clean_gene(Gene),
      ModuleColor = as.character(ModuleColor)
    )

  hubs <- read_csv_flexible(file.path(run_dir, "04_hub_genes", "AllGenes_kME_GS.csv")) |>
    dplyr::mutate(
      Gene = clean_gene(Gene),
      ModuleColor = as.character(ModuleColor)
    )

  ## IMPORTANT: ModuleColor must be retained because the join uses Gene + ModuleColor.
  keep_hub <- intersect(
    c("Gene", "ModuleColor", "kME", "GS_Temperature", "GS_Treatment", "GS_Time",
      "IsHub", "IsHighGS_Temp", "IsHighGS_Trt"),
    colnames(hubs)
  )

  hub_small <- hubs |>
    dplyr::select(dplyr::all_of(keep_hub)) |>
    dplyr::distinct(Gene, ModuleColor, .keep_all = TRUE)

  out <- gene_mod |>
    dplyr::select(dplyr::any_of(c("Gene", "ModuleLabel", "ModuleColor"))) |>
    dplyr::distinct(Gene, ModuleColor, .keep_all = TRUE) |>
    dplyr::left_join(hub_small, by = c("Gene", "ModuleColor"))

  ## Create optional columns if an older WGCNA run did not export them.
  optional_numeric <- c("kME", "GS_Temperature", "GS_Treatment", "GS_Time")
  for (nm in optional_numeric) {
    if (!nm %in% colnames(out)) out[[nm]] <- NA_real_
  }
  optional_logical <- c("IsHub", "IsHighGS_Temp", "IsHighGS_Trt")
  for (nm in optional_logical) {
    if (!nm %in% colnames(out)) out[[nm]] <- NA
  }

  out <- out |>
    dplyr::mutate(
      Genotype = genotype,
      In_WGCNA = TRUE,
      kME = as.numeric(kME),
      GS_Temperature = as.numeric(GS_Temperature),
      GS_Treatment = as.numeric(GS_Treatment),
      GS_Time = as.numeric(GS_Time),
      WGCNA_DynamicHub = !is.na(kME) & kME >= KME_HUB_CUTOFF,
      WGCNA_TreatmentPriorityHub =
        WGCNA_DynamicHub & !is.na(GS_Treatment) & abs(GS_Treatment) >= GS_PRIORITY_CUTOFF
    )

  out
}

W_P <- load_wgcna_gene_info("PRESTO", PRESTO_WGCNA)
W_R <- load_wgcna_gene_info("ROBILA", ROBILA_WGCNA)
W_GENE <- bind_rows(W_P, W_R)

##############################
## 5. MODULE EFFECTS — PREFER FULL FACTORIAL INTEGRATION v2
##############################
make_module_effects_fallback <- function(genotype, run_dir) {
  a <- read_csv_flexible(file.path(run_dir, "03_module_trait", "Module_ANOVA_results.csv"))
  a |>
    dplyr::transmute(
      Genotype = genotype,
      ModuleColor = as.character(ModuleColor),
      FDR_Temperature = as.numeric(FDR_Temperature),
      FDR_Treatment = as.numeric(FDR_Treatment),
      FDR_Time = as.numeric(FDR_Time),
      FDR_Temp_x_Treatment = as.numeric(FDR_TempxTrt),
      FDR_Temp_x_Time = NA_real_,
      FDR_Treatment_x_Time = NA_real_,
      FDR_Temp_x_Treatment_x_Time = NA_real_,
      Effect_model_source = "WGCNA module_trait fallback"
    )
}

module_effects <- data.frame()
full_effect_file <- if (!is.na(WGCNA_COMPARATIVE_RUN)) {
  file.path(WGCNA_COMPARATIVE_RUN, "01_tables", "03_ME_TypeIII_full_Temp_Treatment_Time.csv")
} else NA_character_

if (!is.na(full_effect_file) && file.exists(full_effect_file)) {
  fx <- read_csv_flexible(full_effect_file) |>
    dplyr::mutate(
      Genotype = as.character(Genotype),
      ModuleColor = as.character(ModuleColor),
      Effect = as.character(Effect),
      FDR = as.numeric(FDR)
    )

  map_effect <- function(x) {
    x <- gsub("Sampling_time", "Time", x, fixed = TRUE)
    dplyr::recode(
      x,
      "Temperature" = "FDR_Temperature",
      "Treatment" = "FDR_Treatment",
      "Time" = "FDR_Time",
      "Temperature:Treatment" = "FDR_Temp_x_Treatment",
      "Temperature:Time" = "FDR_Temp_x_Time",
      "Treatment:Time" = "FDR_Treatment_x_Time",
      "Temperature:Treatment:Time" = "FDR_Temp_x_Treatment_x_Time",
      .default = NA_character_
    )
  }

  fx <- fx |>
    dplyr::mutate(Effect_key = map_effect(Effect)) |>
    dplyr::filter(!is.na(Effect_key)) |>
    dplyr::select(Genotype, ModuleColor, Effect_key, FDR) |>
    tidyr::pivot_wider(names_from = Effect_key, values_from = FDR)

  expected_fdr_cols <- c(
    "FDR_Temperature", "FDR_Treatment", "FDR_Time",
    "FDR_Temp_x_Treatment", "FDR_Temp_x_Time",
    "FDR_Treatment_x_Time", "FDR_Temp_x_Treatment_x_Time"
  )
  for (nm in expected_fdr_cols) if (!nm %in% colnames(fx)) fx[[nm]] <- NA_real_

  module_effects <- fx |>
    dplyr::mutate(Effect_model_source = "Integration v2 full factorial Type III")
} else {
  module_effects <- bind_rows(
    make_module_effects_fallback("PRESTO", PRESTO_WGCNA),
    make_module_effects_fallback("ROBILA", ROBILA_WGCNA)
  )
}

module_effects <- module_effects |>
  dplyr::mutate(
    Temperature_recruited =
      (!is.na(FDR_Temperature) & FDR_Temperature < FDR_CUTOFF) |
      (!is.na(FDR_Temp_x_Time) & FDR_Temp_x_Time < FDR_CUTOFF),
    Treatment_recruited =
      (!is.na(FDR_Treatment) & FDR_Treatment < FDR_CUTOFF) |
      (!is.na(FDR_Treatment_x_Time) & FDR_Treatment_x_Time < FDR_CUTOFF),
    Time_recruited = !is.na(FDR_Time) & FDR_Time < FDR_CUTOFF,
    Temp_x_Treatment_recruited =
      (!is.na(FDR_Temp_x_Treatment) & FDR_Temp_x_Treatment < FDR_CUTOFF) |
      (!is.na(FDR_Temp_x_Treatment_x_Time) & FDR_Temp_x_Treatment_x_Time < FDR_CUTOFF),
    Temp_x_Time_recruited = !is.na(FDR_Temp_x_Time) & FDR_Temp_x_Time < FDR_CUTOFF,
    Treatment_x_Time_recruited = !is.na(FDR_Treatment_x_Time) & FDR_Treatment_x_Time < FDR_CUTOFF,
    Triple_interaction_recruited =
      !is.na(FDR_Temp_x_Treatment_x_Time) & FDR_Temp_x_Treatment_x_Time < FDR_CUTOFF,
    Statistical_module_class = dplyr::case_when(
      Triple_interaction_recruited ~ "Temperature x Treatment x Time",
      Temp_x_Treatment_recruited ~ "Temperature x Treatment",
      Temperature_recruited & Treatment_recruited ~ "Temperature + Treatment",
      Temperature_recruited ~ "Temperature",
      Treatment_recruited ~ "Treatment",
      Time_recruited ~ "Time-associated",
      TRUE ~ "No significant tested effect"
    )
  )

write_csv(module_effects, file.path(DIR_TABLES, "01_Module_effect_classification.csv"))

W_GENE <- W_GENE |>
  dplyr::left_join(module_effects, by = c("Genotype", "ModuleColor"))

##############################
## 6. LOAD maSigPro MEMBERSHIP
##############################
load_masig_info <- function(genotype, masig_dir) {
  cl <- read_csv_flexible(file.path(masig_dir, "04_tables", "Gene_cluster_assignment.csv")) |>
    dplyr::transmute(Gene = clean_gene(Gene), maSigPro_cluster = as.integer(Cluster))

  strict_file <- file.path(masig_dir, "04_tables", "maSigPro_strict_genes_Tfit.csv")
  strict <- if (file.exists(strict_file)) {
    read_csv_flexible(strict_file) |> dplyr::transmute(Gene = clean_gene(Gene), maSigPro_strict = TRUE)
  } else {
    data.frame(Gene = character(), maSigPro_strict = logical())
  }

  cl |>
    dplyr::left_join(strict, by = "Gene") |>
    dplyr::mutate(
      maSigPro_strict = tidyr::replace_na(maSigPro_strict, FALSE),
      In_maSigPro = TRUE,
      Genotype = genotype
    )
}

M_P <- load_masig_info("PRESTO", PRESTO_MASIG)
M_R <- load_masig_info("ROBILA", ROBILA_MASIG)
M_GENE <- bind_rows(M_P, M_R)

##############################
## 7. MERGE CURRENT GENE-LEVEL ANALYSES
##############################
MASTER_BASE <- full_join(
  W_GENE,
  M_GENE,
  by = c("Gene", "Genotype")
) |>
  dplyr::mutate(
    In_WGCNA = tidyr::replace_na(In_WGCNA, FALSE),
    In_maSigPro = tidyr::replace_na(In_maSigPro, FALSE),
    maSigPro_strict = tidyr::replace_na(maSigPro_strict, FALSE),
    Dynamic_in_both = In_WGCNA & In_maSigPro,
    Strict_dynamic_in_both = In_WGCNA & In_maSigPro & maSigPro_strict
  )

## If the dedicated WGCNA x maSigPro integration exists, use its strict
## integration flags as an additional consistency layer.
if (!is.na(WGCNA_MASIGPRO_RUN)) {
  f_dyn <- file.path(
    WGCNA_MASIGPRO_RUN,
    "01_tables",
    "03_All_maSigPro_dynamic_genes_with_WGCNA_membership.csv"
  )
  if (file.exists(f_dyn)) {
    dyn <- read_csv_flexible(f_dyn) |>
      dplyr::mutate(Gene = clean_gene(Gene), Genotype = as.character(Genotype)) |>
      dplyr::transmute(
        Gene, Genotype,
        Integrated_maSigPro_cluster = as.integer(Cluster),
        Integrated_WGCNA_module = as.character(ModuleColor),
        Integrated_kME = as.numeric(kME),
        Integrated_DynamicHub = as.logical(DynamicHub),
        Integrated_DynamicTreatmentHub = as.logical(DynamicTreatmentHub)
      )
    MASTER_BASE <- MASTER_BASE |>
      dplyr::left_join(dyn, by = c("Gene", "Genotype"))
  }
}

##############################
## 8. HSP ANNOTATION — SAME CORE RULES AS 09A
##############################
assert_file(HSP_ANNOT_FILE, "HSP annotation")
hsp_raw <- read_csv_flexible(HSP_ANNOT_FILE)
if (!all(c("my_gene_id", "gene_ID", "func_clean") %in% colnames(hsp_raw))) {
  stop("HSP annotation must contain my_gene_id, gene_ID and func_clean.")
}

classify_hsp_annotations <- function(tbl) {
  tbl |>
    dplyr::mutate(
      annotation_raw = dplyr::coalesce(as.character(func_clean), ""),
      annotation_lc = stringr::str_to_lower(annotation_raw),
      fp_groes_enzyme = stringr::str_detect(annotation_lc,
        "alcohol dehydrogenase groes-like|cinnamyl alcohol dehydrogenase|zinc-binding dehydrogenase|zinc-containing alcohol dehydrogenases|quinone oxidoreductase"),
      fp_hsp70_nbd = stringr::str_detect(annotation_lc, "nbd_sugar-kinase_hsp70_actin") &
        !stringr::str_detect(annotation_lc,
          "hsp70 protein|heat shock 70|heat shock protein 70|70kda heat shock|chaperone protein dnak|molecular chaperone dnak|hspa[0-9]"),
      fp_hsp90_hatpase = stringr::str_detect(annotation_lc,
        "histidine kinase|ethylene receptor|phytochrome|pyruvate dehydrogenase.*kinase|branched-chain alpha-ketoacid dehydrogenase kinase") &
        !stringr::str_detect(annotation_lc,
          "hsp90 protein|heat shock protein 90|heat shock 90|90kda heat shock protein signature|heat shock hsp90 proteins family|endoplasmin|grp94|chaperone protein htpg"),
      ambiguous_acd_enzyme = stringr::str_detect(annotation_lc,
        "hsp20/alpha crystallin|small heat shock protein.*domain|acd_") &
        stringr::str_detect(annotation_lc,
          "udp-gluc|udp-glycosyl|glycosyltransferase|lipase|acylhydrolase|polysaccharide lyase"),
      is_cochaperone = stringr::str_detect(annotation_lc,
        "activator of hsp90 atpase|\\baha1\\b|stress-induced phosphoprotein|hsp70/hsp90-organizing|hsp70-hsp90 organizing|\\bsti1\\b|\\bhop\\b|hsp70-binding protein|nucleotide exchange factor fes1|\\bfes1\\b|hspbp"),
      is_hsp100 = stringr::str_detect(annotation_lc,
        "atp-dependent chaperone clpb|chaperone[_ ]clpb|chaperone protein clpb|chaperone clpb|clpa/b signature|\\bhsp100\\b|\\bhsp101\\b"),
      is_hsp90 = stringr::str_detect(annotation_lc,
        "hsp90 protein|heat shock protein 90|heat shock 90|90kda heat shock protein signature|heat shock hsp90 proteins family|endoplasmin|grp94|chaperone protein htpg|hatpase_hsp90-like"),
      is_hsp70 = stringr::str_detect(annotation_lc,
        "hsp70 protein|heat shock 70|heat shock protein 70|70kda heat shock protein signature|heat shock hsp70 proteins family|chaperone protein dnak|molecular chaperone dnak|luminal-binding protein|stromal 70 kda|hspa[0-9]|hsca homolog"),
      is_cct = stringr::str_detect(annotation_lc,
        "t-complex protein|tailless complex polypeptide|tcp1_|chaperonins tcp-1|chap_cct|\\bcct\\b"),
      is_hsp10 = stringr::str_detect(annotation_lc,
        "\\bcpn10\\b|10kda chaperonin|10 kda chaperonin|chaperonin 10"),
      is_hsp60 = stringr::str_detect(annotation_lc,
        "chaperonin groel|\\bgroel\\b|60 kda chaperonin|60kda chaperonin|chaperonins cpn60|\\bcpn60\\b") & !is_cct,
      is_dnaj = stringr::str_detect(annotation_lc,
        "dnaj domain|dnaj domain signature|dnaj domain profile|\\bdnaj\\b|molecular chaperone dnaj|chaperone protein dnaj"),
      is_shsp = stringr::str_detect(annotation_lc,
        "hsp20/alpha crystallin|small heat shock protein|small hsp|17\\.[0-9]+ kda class|26\\.[0-9]+ kda heat shock|acd_shsp|acd_schsp"),
      HSP_exclusion_reason = dplyr::case_when(
        fp_groes_enzyme ~ "GroES-like enzyme false positive",
        fp_hsp70_nbd ~ "Generic HSP70/actin NBD false positive",
        fp_hsp90_hatpase ~ "Generic HATPase kinase/receptor false positive",
        ambiguous_acd_enzyme ~ "Ambiguous alpha-crystallin catalytic protein",
        TRUE ~ NA_character_
      ),
      HSP_family = dplyr::case_when(
        !is.na(HSP_exclusion_reason) ~ NA_character_,
        is_cochaperone ~ "Co-chaperones",
        is_hsp100 ~ "HSP100 / ClpB",
        is_hsp90 ~ "HSP90",
        is_hsp70 ~ "HSP70 / HSC70",
        is_cct ~ "CCT / TCP-1",
        is_hsp10 ~ "HSP10 / Cpn10",
        is_hsp60 ~ "HSP60 / Cpn60",
        is_dnaj ~ "HSP40 / DnaJ",
        is_shsp ~ "HSP20 / sHSP",
        TRUE ~ NA_character_
      ),
      HSP_subfamily = dplyr::case_when(
        is_cochaperone & stringr::str_detect(annotation_lc, "aha1|activator of hsp90") ~ "Aha1",
        is_cochaperone & stringr::str_detect(annotation_lc, "sti1|stress-induced phosphoprotein|organizing|\\bhop\\b") ~ "HOP / STI1",
        is_cochaperone & stringr::str_detect(annotation_lc, "fes1|hsp70-binding|hspbp") ~ "HSP70 nucleotide-exchange factor",
        is_cochaperone ~ "Other co-chaperone",
        is_hsp100 & stringr::str_detect(annotation_lc, "clpb3|chloroplast|chloroplastic|plastid") ~ "ClpB3-like, chloroplast",
        is_hsp100 & stringr::str_detect(annotation_lc, "mitochond") ~ "ClpB-like, mitochondrial",
        is_hsp100 & stringr::str_detect(annotation_lc, "hsp101|atp-dependent chaperone clpb|chaperone[_ ]clpb|chaperone protein clpb") ~ "ClpB / HSP101-like",
        is_hsp100 ~ "HSP100/ClpA-B-like, localisation unresolved",
        is_hsp90 & stringr::str_detect(annotation_lc, "endoplasmin|grp94") ~ "ER HSP90 / endoplasmin",
        is_hsp90 & stringr::str_detect(annotation_lc, "hsp90-5|chloroplast|chloroplastic|plastid") ~ "Chloroplast HSP90",
        is_hsp90 & stringr::str_detect(annotation_lc, "hsp90-6|mitochond") ~ "Mitochondrial HSP90",
        is_hsp90 & stringr::str_detect(annotation_lc, "cytosol|cytosolic") ~ "Cytosolic HSP90-like",
        is_hsp90 ~ "HSP90-like, localisation unresolved",
        is_hsp70 & stringr::str_detect(annotation_lc, "luminal-binding|hspa5|\\bbip\\b") ~ "ER BiP / HSPA5-like",
        is_hsp70 & stringr::str_detect(annotation_lc, "stromal|chloroplast|chloroplastic|plastid") ~ "Chloroplast HSP70",
        is_hsp70 & stringr::str_detect(annotation_lc, "hspa9|heat shock protein 9|mitochond") ~ "Mitochondrial HSP70-like",
        is_hsp70 & stringr::str_detect(annotation_lc, "hspa4|heat shock 70 kda protein 4") ~ "HSP110 / HSPH-like",
        is_hsp70 & stringr::str_detect(annotation_lc, "heat shock cognate|hsc70") ~ "HSC70-like",
        is_hsp70 & stringr::str_detect(annotation_lc, "cytosol|cytosolic") ~ "Cytosolic HSP70-like",
        is_hsp70 ~ "HSP70-like, localisation unresolved",
        is_cct & stringr::str_detect(annotation_lc, "delta") ~ "CCT delta subunit",
        is_cct ~ "CCT / TCP-1 subunit",
        is_hsp10 & stringr::str_detect(annotation_lc, "mitochond") ~ "Mitochondrial Cpn10",
        is_hsp10 & stringr::str_detect(annotation_lc, "chloroplast|chloroplastic|plastid") ~ "Chloroplast Cpn10",
        is_hsp10 ~ "Cpn10",
        is_hsp60 & stringr::str_detect(annotation_lc, "chloroplast|chloroplastic|plastid") ~ "Chloroplast Cpn60",
        is_hsp60 & stringr::str_detect(annotation_lc, "mitochond") ~ "Mitochondrial Cpn60",
        is_hsp60 ~ "Cpn60 / GroEL-like",
        is_dnaj & stringr::str_detect(annotation_lc, "dnaj_zf|zinc finger cr-type") & stringr::str_detect(annotation_lc, "dnaj_c|dnaj c terminal") ~ "DnaJ-A-like",
        is_dnaj & !stringr::str_detect(annotation_lc, "dnaj_zf|zinc finger cr-type") & stringr::str_detect(annotation_lc, "dnaj_c|dnaj c terminal") ~ "DnaJ-B-like",
        is_dnaj & stringr::str_detect(annotation_lc, "dnaj domain|dnaj domain signature|dnaj domain profile") ~ "DnaJ-C-like",
        is_dnaj ~ "DnaJ-related, domain incomplete",
        is_shsp & stringr::str_detect(annotation_lc, "class ii") ~ "Cytosolic class II sHSP",
        is_shsp & stringr::str_detect(annotation_lc, "class i") ~ "Cytosolic class I sHSP",
        is_shsp & stringr::str_detect(annotation_lc, "mitochond") ~ "Mitochondrial sHSP",
        is_shsp & stringr::str_detect(annotation_lc, "chloroplast|chloroplastic|plastid") ~ "Chloroplast sHSP",
        is_shsp ~ "sHSP / ACD protein",
        TRUE ~ NA_character_
      ),
      Is_HSP = !is.na(HSP_family)
    ) |>
    dplyr::select(Gene, HSP_gene_ID = gene_ID, HSP_function = func_clean,
                  HSP_family, HSP_subfamily, HSP_exclusion_reason, Is_HSP)
}

HSP_ANNOT <- hsp_raw |>
  dplyr::transmute(
    Gene = clean_gene(my_gene_id),
    gene_ID = clean_gene(gene_ID),
    func_clean = as.character(func_clean)
  ) |>
  dplyr::distinct(Gene, .keep_all = TRUE) |>
  classify_hsp_annotations()

## Reuse manual curation from the latest old 09A run when available.
legacy_hsp_curated <- latest_named_file(c(LEGACY_P1_ROOT), "HSP_family_curated.csv")
if (!is.na(legacy_hsp_curated)) {
  hc <- read_csv_flexible(legacy_hsp_curated)
  if (all(c("Gene", "HSP_family", "HSP_subfamily") %in% colnames(hc))) {
    hc <- hc |>
      dplyr::transmute(
        Gene = clean_gene(Gene),
        HSP_family_manual = as.character(HSP_family),
        HSP_subfamily_manual = as.character(HSP_subfamily),
        HSP_include_manual = if ("Include" %in% colnames(hc)) as.logical(Include) else TRUE
      ) |>
      dplyr::distinct(Gene, .keep_all = TRUE)
    HSP_ANNOT <- HSP_ANNOT |>
      dplyr::left_join(hc, by = "Gene") |>
      dplyr::mutate(
        HSP_family = dplyr::if_else(
          !is.na(HSP_family_manual) & nzchar(HSP_family_manual) & HSP_include_manual,
          HSP_family_manual, HSP_family
        ),
        HSP_subfamily = dplyr::if_else(
          !is.na(HSP_subfamily_manual) & nzchar(HSP_subfamily_manual) & HSP_include_manual,
          HSP_subfamily_manual, HSP_subfamily
        ),
        Is_HSP = !is.na(HSP_family)
      ) |>
      dplyr::select(-HSP_family_manual, -HSP_subfamily_manual, -HSP_include_manual)
  }
}
write_csv(HSP_ANNOT, file.path(DIR_ANNOT, "HSP_annotation_master.csv"))

##############################
## 9. TF ANNOTATION — REUSE ALL-GENE OUTPUT FROM 09B
##############################
legacy_tf_all <- latest_named_file(c(LEGACY_P1_ROOT), "TF_annotation_mapped_all.csv")
if (is.na(legacy_tf_all)) {
  stop(
    "TF_annotation_mapped_all.csv was not found under LEGACY_P1_ROOT. ",
    "Run script 09B once, or set LEGACY_P1_ROOT to the directory containing its 03_QC output."
  )
}

TF_RAW <- read_csv_flexible(legacy_tf_all)
tf_gene_col <- first_existing_col(TF_RAW, c("my_gene_id", "Gene"))
if (is.na(tf_gene_col)) stop("Cannot identify TF gene ID column in: ", legacy_tf_all)

TF_ANNOT <- TF_RAW |>
  dplyr::mutate(Gene = clean_gene(.data[[tf_gene_col]])) |>
  dplyr::transmute(
    Gene,
    TF_gene_ID = if ("gene_ID" %in% colnames(TF_RAW)) as.character(gene_ID) else NA_character_,
    TF_type = if ("tf_type" %in% colnames(TF_RAW)) as.character(tf_type) else NA_character_,
    TF_family = if ("TF_family" %in% colnames(TF_RAW)) as.character(TF_family) else
      if ("TF_family_source" %in% colnames(TF_RAW)) as.character(TF_family_source) else NA_character_,
    TF_subgroup = if ("TF_subgroup" %in% colnames(TF_RAW)) as.character(TF_subgroup) else NA_character_,
    TF_annotation_confidence = if ("Annotation_confidence" %in% colnames(TF_RAW)) as.character(Annotation_confidence) else NA_character_,
    TF_function = if ("func_clean" %in% colnames(TF_RAW)) as.character(func_clean) else NA_character_,
    Is_TF = TRUE
  ) |>
  dplyr::distinct(Gene, .keep_all = TRUE)

write_csv(TF_ANNOT, file.path(DIR_ANNOT, "TF_annotation_master.csv"))

##############################
## 10. IMMUNE ANNOTATION — EXACT ALL-GENE CLASSIFIER OUTPUT FROM 09C
##############################
legacy_immune_all <- latest_named_file(c(LEGACY_P1_ROOT), "immune_classifier_all_mapped_genes.csv")
if (is.na(legacy_immune_all)) {
  stop(
    "immune_classifier_all_mapped_genes.csv was not found under LEGACY_P1_ROOT. ",
    "This file is the exact all-gene output of script 09C and is deliberately required ",
    "to preserve the same immune-classification logic without simplifying it."
  )
}

IMM_RAW <- read_csv_flexible(legacy_immune_all)
imm_gene_col <- first_existing_col(IMM_RAW, c("Gene", "my_gene_id"))
if (is.na(imm_gene_col)) stop("Cannot identify immune gene ID column in: ", legacy_immune_all)

IMMUNE_ANNOT <- IMM_RAW |>
  dplyr::mutate(Gene = clean_gene(.data[[imm_gene_col]])) |>
  dplyr::transmute(
    Gene,
    Immune_module = if ("Immune_module_auto" %in% colnames(IMM_RAW)) as.character(Immune_module_auto) else
      if ("Immune_module" %in% colnames(IMM_RAW)) as.character(Immune_module) else NA_character_,
    Immune_submodule = if ("Immune_submodule_auto" %in% colnames(IMM_RAW)) as.character(Immune_submodule_auto) else
      if ("Immune_submodule" %in% colnames(IMM_RAW)) as.character(Immune_submodule) else NA_character_,
    Immune_evidence = if ("Evidence_level_auto" %in% colnames(IMM_RAW)) as.character(Evidence_level_auto) else
      if ("Evidence_level" %in% colnames(IMM_RAW)) as.character(Evidence_level) else NA_character_,
    Direct_heat_immunity_anchor = if ("Direct_heat_immunity_anchor" %in% colnames(IMM_RAW)) as.logical(Direct_heat_immunity_anchor) else FALSE,
    Immune_annotation = if ("annotation_raw" %in% colnames(IMM_RAW)) as.character(annotation_raw) else
      if ("annotation_text" %in% colnames(IMM_RAW)) as.character(annotation_text) else NA_character_,
    Is_Immune = !is.na(Immune_module) & nzchar(Immune_module)
  ) |>
  dplyr::distinct(Gene, .keep_all = TRUE)

write_csv(IMMUNE_ANNOT, file.path(DIR_ANNOT, "Immune_annotation_master.csv"))

##############################
## 11. FUNCTIONAL FAMILY MEMBERSHIP — SAME INPUT ROOT AS SCRIPT 10
##############################
FUNCTIONAL_FAMILY_DIRS <- c(
  "01_Protein_Folding_Processing_Degradation",
  "02_Hormone_Signaling_Metabolism",
  "03_MAPK_Calcium_Stress_Signaling",
  "04_Photosynthesis_Energy_Metabolism",
  "05_Terpenoid_Secondary_Metabolism",
  "06_ROS_Redox_Glutathione",
  "07_Lipid_Membrane_Metabolism",
  "08_Carbon_Starch_Sucrose_Osmoprotection"
)
FUNCTIONAL_FAMILY_LABELS <- c(
  "01_Protein_Folding_Processing_Degradation" = "Protein folding, processing and degradation",
  "02_Hormone_Signaling_Metabolism" = "Hormone signalling and metabolism",
  "03_MAPK_Calcium_Stress_Signaling" = "MAPK, calcium and stress signalling",
  "04_Photosynthesis_Energy_Metabolism" = "Photosynthesis and energy metabolism",
  "05_Terpenoid_Secondary_Metabolism" = "Terpenoid and specialised metabolism",
  "06_ROS_Redox_Glutathione" = "ROS, redox and glutathione metabolism",
  "07_Lipid_Membrane_Metabolism" = "Lipid and membrane metabolism",
  "08_Carbon_Starch_Sucrose_Osmoprotection" = "Carbon, starch, sucrose and osmoprotection"
)

read_one_functional_family <- function(fam_dir) {
  folder <- file.path(FUNCTIONAL_INPUT_DIR, fam_dir)
  if (!dir.exists(folder)) return(data.frame())

  sf_file <- list.files(folder, full.names = TRUE, pattern = "_subfamily_assignment\\.csv$")
  pr_file <- list.files(folder, full.names = TRUE, pattern = "_KEGG_provenance\\.csv$")
  if (!length(sf_file) && !length(pr_file)) return(data.frame())

  sf <- if (length(sf_file)) read_csv_flexible(sf_file[1]) else data.frame()
  pr <- if (length(pr_file)) read_csv_flexible(pr_file[1]) else data.frame()

  sf2 <- if (nrow(sf)) {
    gcol <- first_existing_col(sf, c("Gene", "my_gene_id"))
    scol <- first_existing_col(sf, c("Subfamily", "subfamily"))
    if (!is.na(gcol)) {
      sf |>
        dplyr::transmute(
          Gene = clean_gene(.data[[gcol]]),
          Functional_subfamily_source = if (!is.na(scol)) as.character(.data[[scol]]) else NA_character_
        ) |>
        dplyr::distinct(Gene, .keep_all = TRUE)
    } else data.frame()
  } else data.frame()

  pr2 <- if (nrow(pr)) {
    gcol <- first_existing_col(pr, c("my_gene_id", "Gene"))
    if (!is.na(gcol)) {
      pr |>
        dplyr::mutate(Gene = clean_gene(.data[[gcol]])) |>
        dplyr::group_by(Gene) |>
        dplyr::summarise(
          Functional_KEGG_pathways = collapse_unique(if ("Pathway" %in% colnames(pr)) Pathway else character()),
          Functional_KEGG_pathway_num = collapse_unique(if ("pathway_num" %in% colnames(pr)) pathway_num else character()),
          Functional_annotation = collapse_unique(if ("func_clean" %in% colnames(pr)) func_clean else character()),
          .groups = "drop"
        )
    } else data.frame()
  } else data.frame()

  z <- full_join(sf2, pr2, by = "Gene")
  if (!nrow(z)) return(data.frame())
  z |>
    dplyr::mutate(
      Functional_family_ID = fam_dir,
      Functional_family = unname(FUNCTIONAL_FAMILY_LABELS[fam_dir])
    )
}

FUNCTIONAL_LONG <- purrr::map_dfr(FUNCTIONAL_FAMILY_DIRS, read_one_functional_family)

## Reuse refined script-10 curation for genes that were already manually/
## automatically resolved there; retain source membership for all other genes.
legacy_functional_curated <- latest_named_file(c(LEGACY_P1_ROOT), "Functional_family_curated.csv")
if (!is.na(legacy_functional_curated)) {
  fc <- read_csv_flexible(legacy_functional_curated)
  if (all(c("Gene", "Family_ID", "Subfamily") %in% colnames(fc))) {
    fc <- fc |>
      dplyr::transmute(
        Gene = clean_gene(Gene),
        Functional_family_ID = as.character(Family_ID),
        Functional_subfamily_refined = as.character(Subfamily),
        Functional_short_name = if ("Short_name" %in% colnames(fc)) as.character(Short_name) else NA_character_,
        Functional_classification_confidence = if ("Classification_confidence" %in% colnames(fc)) as.character(Classification_confidence) else NA_character_
      ) |>
      dplyr::distinct(Gene, Functional_family_ID, .keep_all = TRUE)

    FUNCTIONAL_LONG <- FUNCTIONAL_LONG |>
      dplyr::left_join(fc, by = c("Gene", "Functional_family_ID")) |>
      dplyr::mutate(
        Functional_subfamily = dplyr::coalesce(
          Functional_subfamily_refined,
          Functional_subfamily_source
        )
      )
  } else {
    FUNCTIONAL_LONG$Functional_subfamily <- FUNCTIONAL_LONG$Functional_subfamily_source
  }
} else {
  FUNCTIONAL_LONG$Functional_subfamily <- FUNCTIONAL_LONG$Functional_subfamily_source
}

write_csv(FUNCTIONAL_LONG, file.path(DIR_ANNOT, "Functional_annotation_long_master.csv"))

FUNCTIONAL_COLLAPSED <- FUNCTIONAL_LONG |>
  dplyr::group_by(Gene) |>
  dplyr::summarise(
    Functional_families = collapse_unique(Functional_family),
    Functional_subfamilies = collapse_unique(Functional_subfamily),
    Functional_KEGG_pathways = collapse_unique(Functional_KEGG_pathways),
    Functional_annotations = collapse_unique(Functional_annotation),
    Is_FunctionalSet = TRUE,
    .groups = "drop"
  )

##############################
## 12. JOIN BIOLOGICAL ANNOTATION TO CURRENT ANALYSIS
##############################
MASTER <- MASTER_BASE |>
  dplyr::left_join(HSP_ANNOT, by = "Gene") |>
  dplyr::left_join(TF_ANNOT, by = "Gene") |>
  dplyr::left_join(IMMUNE_ANNOT, by = "Gene") |>
  dplyr::left_join(FUNCTIONAL_COLLAPSED, by = "Gene") |>
  dplyr::mutate(
    Is_HSP = tidyr::replace_na(Is_HSP, FALSE),
    Is_TF = tidyr::replace_na(Is_TF, FALSE),
    Is_Immune = tidyr::replace_na(Is_Immune, FALSE),
    Is_FunctionalSet = tidyr::replace_na(Is_FunctionalSet, FALSE),
    Direct_heat_immunity_anchor = tidyr::replace_na(Direct_heat_immunity_anchor, FALSE),

    ## IMPORTANT: these are CANDIDATE heatmap themes, not causal labels.
    Candidate_Temperature =
      Temperature_recruited &
      (Is_HSP | Is_TF | Is_FunctionalSet | Direct_heat_immunity_anchor),

    Candidate_Defence =
      (
        (Treatment_recruited | Treatment_x_Time_recruited) &
          (Is_Immune | Is_TF |
             stringr::str_detect(
               dplyr::coalesce(Functional_families, ""),
               "Hormone|MAPK|ROS|specialised|Lipid"
             ))
      ) |
      ## Time alone is NOT called defence unless the gene is independently
      ## annotated as immune/defence-related.
      (Time_recruited & Is_Immune),

    Candidate_Temp_x_Defence =
      Temp_x_Treatment_recruited &
      (Is_Immune | Is_HSP | Is_TF | Is_FunctionalSet),

    Candidate_PostInoculation_Time =
      Time_recruited,

    Heatmap_primary_theme = dplyr::case_when(
      Candidate_Temp_x_Defence ~ "Temperature x Defence",
      Candidate_Temperature & Candidate_Defence ~ "Temperature + Defence",
      Candidate_Temperature ~ "Temperature",
      Candidate_Defence ~ "Defence",
      Candidate_PostInoculation_Time & Is_Immune ~ "Post-inoculation/time-associated defence",
      TRUE ~ "Other / contextual"
    ),

    Annotation_classes = paste0(
      ifelse(Is_HSP, "HSP;", ""),
      ifelse(Is_TF, "TF;", ""),
      ifelse(Is_Immune, "Immune;", ""),
      ifelse(Is_FunctionalSet, "Functional;", "")
    ),
    Annotation_classes = stringr::str_remove(Annotation_classes, ";$")
  ) |>
  dplyr::arrange(Genotype, ModuleColor, maSigPro_cluster, Gene)

write_csv(MASTER, file.path(DIR_TABLES, "02_Master_gene_annotation_WGCNA_maSigPro.csv"))

## Long version: one row per gene x functional family; useful for script 14.
MASTER_FUNCTIONAL_LONG <- MASTER |>
  dplyr::select(-any_of(c(
    "Functional_families", "Functional_subfamilies",
    "Functional_KEGG_pathways", "Functional_annotations",
    "Is_FunctionalSet"
  ))) |>
  dplyr::left_join(FUNCTIONAL_LONG, by = "Gene")
write_csv(MASTER_FUNCTIONAL_LONG, file.path(DIR_TABLES, "02_Master_gene_annotation_FUNCTIONAL_LONG.csv"))

##############################
## 13. EXPRESSION MATRIX FOR WGCNA HEATMAPS: D2 + D4
##############################
mean_wgcna_expression <- function(genotype, run_dir) {
  datExpr <- readRDS(file.path(run_dir, "02_network", "datExpr_clean.rds"))
  meta <- readRDS(file.path(run_dir, "02_network", "meta_clean.rds"))

  datExpr <- as.data.frame(datExpr)
  if (is.null(rownames(datExpr))) stop("datExpr has no sample rownames: ", run_dir)
  meta$Sample <- as.character(meta$Sample)
  idx <- match(rownames(datExpr), meta$Sample)
  if (anyNA(idx)) stop("Could not align datExpr with metadata for ", genotype)
  meta <- meta[idx, , drop = FALSE]

  temp <- normalise_temp_display(meta$Temperature)
  trt <- normalise_trt_display(meta$Treatment)
  tim <- normalise_time_display(meta$Sampling_time)
  group <- paste(genotype, temp, trt, tim, sep = "_")

  groups <- unique(group)
  means <- vapply(groups, function(g) {
    rows <- which(group == g)
    colMeans(datExpr[rows, , drop = FALSE], na.rm = TRUE)
  }, FUN.VALUE = numeric(ncol(datExpr)))

  rownames(means) <- colnames(datExpr)
  as.data.frame(means) |>
    tibble::rownames_to_column("Gene")
}

EXPR_W_P <- mean_wgcna_expression("PRESTO", PRESTO_WGCNA)
EXPR_W_R <- mean_wgcna_expression("ROBILA", ROBILA_WGCNA)
EXPR_WGCNA <- full_join(EXPR_W_P, EXPR_W_R, by = "Gene")
write_csv(EXPR_WGCNA, file.path(DIR_EXPR, "Expression_mean_WGCNA_D2_D4_bothGenotypes.csv"))

##############################
## 14. EXPRESSION MATRIX FOR maSigPro HEATMAPS: D0 + D2 + D4
## D0 = pre-treatment baseline only (3 columns/genotype)
##############################
mean_masig_expression <- function(genotype, masig_dir) {
  expr <- readRDS(file.path(masig_dir, "00_inputs", "expr_vst_after_MAD.rds"))
  meta <- read_csv_flexible(file.path(masig_dir, "00_inputs", "metadata_filtered.csv"))

  if (is.null(rownames(expr))) stop("maSigPro expression matrix has no gene rownames: ", genotype)
  meta$Sample <- sprintf("%04d", as.integer(as.character(meta$Sample)))
  keep <- meta$Sample %in% colnames(expr)
  meta <- meta[keep, , drop = FALSE]

  temp_levels <- c("T0", "T1", "T2")
  time_levels <- c("P1", "P2", "P3")

  out <- list()
  for (tt in temp_levels) {
    for (tm in time_levels) {

      ## -------------------------------------------------------------
      ## D0/P1 is PRE-TREATMENT.
      ## There is ONE baseline per temperature, not Control + Treated.
      ## The duplicated D0 used internally in maSigPro is a modelling
      ## device only and must never appear as a separate heatmap column.
      ## -------------------------------------------------------------
      if (tm == "P1") {
        samps <- meta$Sample[
          as.character(meta$Temperature) == tt &
          as.character(meta$Treatment) == "EAU" &
          as.character(meta$Sampling_time) == tm
        ]
        samps <- intersect(samps, colnames(expr))
        if (!length(samps)) next

        nm <- paste(
          genotype,
          normalise_temp_display(tt),
          "Baseline",
          normalise_time_display(tm),
          sep = "_"
        )
        out[[nm]] <- rowMeans(expr[, samps, drop = FALSE], na.rm = TRUE)

      } else {
        ## D2/P2 and D4/P3: Control and Treated are real conditions.
        for (tr in c("EAU", "SDP")) {
          samps <- meta$Sample[
            as.character(meta$Temperature) == tt &
            as.character(meta$Treatment) == tr &
            as.character(meta$Sampling_time) == tm
          ]
          samps <- intersect(samps, colnames(expr))
          if (!length(samps)) next

          nm <- paste(
            genotype,
            normalise_temp_display(tt),
            normalise_trt_display(tr),
            normalise_time_display(tm),
            sep = "_"
          )
          out[[nm]] <- rowMeans(expr[, samps, drop = FALSE], na.rm = TRUE)
        }
      }
    }
  }

  if (!length(out)) stop("No maSigPro heatmap conditions generated for ", genotype)

  mat <- do.call(cbind, out)
  rownames(mat) <- rownames(expr)
  as.data.frame(mat) |>
    tibble::rownames_to_column("Gene")
}

EXPR_M_P <- mean_masig_expression("PRESTO", PRESTO_MASIG)
EXPR_M_R <- mean_masig_expression("ROBILA", ROBILA_MASIG)
EXPR_MASIG <- full_join(EXPR_M_P, EXPR_M_R, by = "Gene")
write_csv(EXPR_MASIG, file.path(DIR_EXPR, "Expression_mean_maSigPro_D0_D2_D4_bothGenotypes.csv"))

##############################
## 15. FUNCTIONAL ENRICHMENT TABLES FOR DOWNSTREAM LABELS
##############################
read_wgcna_enrichment <- function(genotype, run_dir) {
  go <- safe_read_csv(file.path(run_dir, "05_enrichment", "GO_ALL_modules_combined.csv"))
  pw <- safe_read_csv(file.path(run_dir, "05_enrichment", "Pathway_ALL_modules_combined.csv"))

  if (nrow(go)) {
    go <- go |>
      dplyr::mutate(Genotype = genotype, Analysis = "WGCNA", Source = "GO", Unit = as.character(Module))
  }
  if (nrow(pw)) {
    pw <- pw |>
      dplyr::mutate(Genotype = genotype, Analysis = "WGCNA", Source = "Pathway", Unit = as.character(Module))
  }
  bind_rows(go, pw)
}

read_masig_enrichment <- function(genotype, masig_dir) {
  go <- safe_read_csv(file.path(masig_dir, "05_enrichment", "GO_ALL_combined.csv"))
  pw <- safe_read_csv(file.path(masig_dir, "05_enrichment", "Pathway_ALL_combined.csv"))

  if (nrow(go)) {
    go <- go |>
      dplyr::mutate(Genotype = genotype, Analysis = "maSigPro", Source = "GO", Unit = as.character(Cluster))
  }
  if (nrow(pw)) {
    pw <- pw |>
      dplyr::mutate(Genotype = genotype, Analysis = "maSigPro", Source = "Pathway", Unit = as.character(Cluster))
  }
  bind_rows(go, pw)
}

ALL_ENRICHMENT <- bind_rows(
  read_wgcna_enrichment("PRESTO", PRESTO_WGCNA),
  read_wgcna_enrichment("ROBILA", ROBILA_WGCNA),
  read_masig_enrichment("PRESTO", PRESTO_MASIG),
  read_masig_enrichment("ROBILA", ROBILA_MASIG)
)
write_csv(ALL_ENRICHMENT, file.path(DIR_TABLES, "03_All_WGCNA_maSigPro_GO_Pathway_terms.csv"))

##############################
## 16. READY-TO-USE GENE SETS FOR THE NEXT SCRIPTS
##############################
GENESETS <- bind_rows(
  MASTER |> filter(Candidate_Temperature) |> transmute(Genotype, Gene, GeneSet = "Temperature_all"),
  MASTER |> filter(Candidate_Defence) |> transmute(Genotype, Gene, GeneSet = "Defence_all"),
  MASTER |> filter(Candidate_Temp_x_Defence) |> transmute(Genotype, Gene, GeneSet = "Temperature_x_Defence_all"),
  MASTER |> filter(Candidate_Temperature, Is_HSP) |> transmute(Genotype, Gene, GeneSet = "Temperature_HSP"),
  MASTER |> filter(Candidate_Temperature, Is_TF) |> transmute(Genotype, Gene, GeneSet = "Temperature_TF"),
  MASTER |> filter(Candidate_Defence, Is_TF) |> transmute(Genotype, Gene, GeneSet = "Defence_TF"),
  MASTER |> filter(Candidate_Defence, Is_Immune) |> transmute(Genotype, Gene, GeneSet = "Defence_Immune"),
  MASTER |> filter(Candidate_Temp_x_Defence, Is_Immune) |> transmute(Genotype, Gene, GeneSet = "Temperature_x_Defence_Immune"),
  MASTER |> filter(Candidate_Temp_x_Defence, Is_HSP) |> transmute(Genotype, Gene, GeneSet = "Temperature_x_Defence_HSP")
) |>
  dplyr::distinct()

write_csv(GENESETS, file.path(DIR_TABLES, "04_Ready_gene_sets_for_heatmaps.csv"))

##############################
## 17. QC + MANIFEST
##############################
qc_summary <- MASTER |>
  dplyr::group_by(Genotype) |>
  dplyr::summarise(
    N_rows = dplyr::n(),
    N_unique_genes = dplyr::n_distinct(Gene),
    N_WGCNA = sum(In_WGCNA, na.rm = TRUE),
    N_maSigPro = sum(In_maSigPro, na.rm = TRUE),
    N_maSigPro_strict = sum(maSigPro_strict, na.rm = TRUE),
    N_HSP = sum(Is_HSP, na.rm = TRUE),
    N_TF = sum(Is_TF, na.rm = TRUE),
    N_Immune = sum(Is_Immune, na.rm = TRUE),
    N_Functional = sum(Is_FunctionalSet, na.rm = TRUE),
    N_candidate_temperature = sum(Candidate_Temperature, na.rm = TRUE),
    N_candidate_defence = sum(Candidate_Defence, na.rm = TRUE),
    N_candidate_temp_x_defence = sum(Candidate_Temp_x_Defence, na.rm = TRUE),
    .groups = "drop"
  )
write_csv(qc_summary, file.path(DIR_QC, "QC_master_summary.csv"))

module_qc <- MASTER |>
  dplyr::filter(In_WGCNA, ModuleColor != "grey") |>
  dplyr::group_by(Genotype, ModuleColor, Statistical_module_class) |>
  dplyr::summarise(
    N_genes = dplyr::n_distinct(Gene),
    N_HSP = n_distinct(Gene[Is_HSP]),
    N_TF = n_distinct(Gene[Is_TF]),
    N_Immune = n_distinct(Gene[Is_Immune]),
    N_Functional = n_distinct(Gene[Is_FunctionalSet]),
    N_maSigPro = n_distinct(Gene[In_maSigPro]),
    N_maSigPro_strict = n_distinct(Gene[maSigPro_strict]),
    .groups = "drop"
  ) |>
  arrange(Genotype, Statistical_module_class, desc(N_genes))
write_csv(module_qc, file.path(DIR_QC, "QC_module_biological_content.csv"))

manifest <- data.frame(
  Resource = c(
    "PRESTO_WGCNA", "ROBILA_WGCNA", "PRESTO_MASIG", "ROBILA_MASIG",
    "WGCNA_COMPARATIVE_RUN", "WGCNA_MASIGPRO_RUN",
    "HSP_ANNOT_FILE", "TF_ANNOT_ALL", "IMMUNE_CLASSIFIER_ALL",
    "FUNCTIONAL_INPUT_DIR"
  ),
  Path = c(
    PRESTO_WGCNA, ROBILA_WGCNA, PRESTO_MASIG, ROBILA_MASIG,
    WGCNA_COMPARATIVE_RUN, WGCNA_MASIGPRO_RUN,
    HSP_ANNOT_FILE, legacy_tf_all, legacy_immune_all,
    FUNCTIONAL_INPUT_DIR
  ),
  stringsAsFactors = FALSE
)
write_csv(manifest, file.path(DIR_QC, "Input_manifest.csv"))

## Stable pointer for scripts 13A/B/C/14.
writeLines(OUT_DIR, file.path(MASTER_ROOT, "LATEST_MASTER_PATH.txt"))

writeLines(capture.output(sessionInfo()), file.path(OUT_DIR, "sessionInfo.txt"))

##############################
## 18. FINAL REPORT
##############################
log_msg("============================================================")
log_msg("BIOLOGICAL MASTER COMPLETED")
log_msg("Output: ", OUT_DIR)
log_msg("Master rows: ", nrow(MASTER))
log_msg("Unique gene x genotype combinations: ", n_distinct(paste(MASTER$Genotype, MASTER$Gene)))
log_msg("Temperature candidates: ", sum(MASTER$Candidate_Temperature, na.rm = TRUE))
log_msg("Defence candidates: ", sum(MASTER$Candidate_Defence, na.rm = TRUE))
log_msg("Temperature x Defence candidates: ", sum(MASTER$Candidate_Temp_x_Defence, na.rm = TRUE))
log_msg("============================================================")

cat("\n", strrep("=", 70), "\n", sep = "")
cat("13_00 BIOLOGICAL MASTER COMPLETED\n")
cat(strrep("=", 70), "\n", sep = "")
cat("Output: ", OUT_DIR, "\n", sep = "")
cat("\nKEY FILES\n")
cat("  01_tables/01_Module_effect_classification.csv\n")
cat("  01_tables/02_Master_gene_annotation_WGCNA_maSigPro.csv\n")
cat("  01_tables/02_Master_gene_annotation_FUNCTIONAL_LONG.csv\n")
cat("  01_tables/03_All_WGCNA_maSigPro_GO_Pathway_terms.csv\n")
cat("  01_tables/04_Ready_gene_sets_for_heatmaps.csv\n")
cat("  02_expression_matrices/Expression_mean_WGCNA_D2_D4_bothGenotypes.csv\n")
cat("  02_expression_matrices/Expression_mean_maSigPro_D0_D2_D4_bothGenotypes.csv\n")
cat("  04_QC/QC_module_biological_content.csv\n")
cat("\nNEXT: scripts 13A / 13B / 13C / 14 can auto-detect this run via\n")
cat("      Biological_Heatmaps/LATEST_MASTER_PATH.txt\n")
cat(strrep("=", 70), "\n", sep = "")
